### ISSUE TITLE
Feed time zone should be same as set in Wordpress settings.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/gn-publisher#35]
There is another timezone that is picked by the GN feed, it needs to be the same as set up in the WordPress.

Reference Ticket -: https://magazine3.in/conversation/62298?folder_id=23

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
We do not need to setup time zone in feed as google does it automatically based on location.
