### ISSUE TITLE
Need to fix fatal error on feed when testing on Castfeed validator

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/gn-publisher#39]
When we are testing feed on Castfeed validator tool, it is showing fatal error.

Error -: FATAL: Error getting feed contents. This may be due to a bad connection to the server or a problem with HEAD request support. Please retry validation. Did not finish feed tests.

Reference ticket -: https://magazine3.in/conversation/80904?folder_id=23

Tool -: https://www.castfeedvalidator.com/validate.php?url=https://www.heritagedaily.com/category/archaeology-news/feed/gn

**Comment by akshaywali** [comment]
GN Publisher is specifically meant for Google News Feed and it is  generated according to Google News specification.
Our feed passes the validation set for Google News Feed and is compatible for Google News Feed. Same can be verified from https://validator.w3.org/feed/

**Comment by akshaywali** [comment]
Moreover Cast feed validator tool, is podcast feed validation tool not blog feed validator
