### ISSUE TITLE
Conflict issue with pro version

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/gn-publisher#42]
Ref ticket:- https://magazine3.in/conversation/85549?folder_id=21

Description:-
When we activate the GN publisher pro version and plugin dashboard shows blank.

Issue screenshot:-
https://monosnap.com/direct/SFWmFwcDD5EemCqAQHkWeIv8K7f5HM

**Comment by Sanjeevsetu** [comment]
This issue does not seem to valid so I am closing it
