### ISSUE TITLE
512 icon is missing

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/gn-publisher#43]
http://plugins.svn.wordpress.org/gn-publisher/assets/

**Comment by Sanjeevsetu** [comment]
Normal: icon-128x128.(png|jpg)
High-DPI (Retina): icon-256x256.(png|jpg)
SVG: icon.svg
There are no plans to change these sizes.

Above recommendation is written on WP official website. Link : https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

Adding 512 size icon won't be consider by WP so I am closing the ticket
