### ISSUE TITLE
Need to add compatibility with translate press

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/gn-publisher#46]
There is a need to add compatibility with translate press as Google News is not picking multilingual articles.

Reference ticket -: https://magazine3.in/conversation/94663?folder_id=23

Reference link-: https://wordpress.org/plugins/translatepress-multilingual/

**Comment by muslimakhan** [comment]
Pro Changes:
https://github.com/ahmedkaludi/gn-publisher-pro/commit/ce741afcd6b1be53caa8704b1ce496f4a46e80b6
