### ISSUE TITLE
Strip all unnecessary attributes and inline CSS

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/gn-publisher#47]
Strip all unnecessary attributes and inline CSS

Ref ticket: https://magazine3.in/conversation/97409?folder_id=27

**Comment by muslimakhan** [comment]
PRO Changes:
https://github.com/ahmedkaludi/gn-publisher-pro/commit/0b04034e139f3161ad28baf3cd0551a9cb883c5d

**Comment by muslimakhan** [comment]
PRO Revert Changes:
https://github.com/ahmedkaludi/gn-publisher-pro/commit/a2f0bd97f5074c3302cdf3d00f73a042a184df0a
