### ISSUE TITLE
Need to add feature exclude categories from feed.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/gn-publisher#48]
Ref ticket:- https://magazine3.in/conversation/104293?folder_id=21

Description:-
Exclude certain categories from the feed.

**Comment by sajandara** [comment]
https://magazine3.in/conversation/119937?folder_id=27

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/gn-publisher-pro/commit/f3c2b91ca928eb377b5c4f38c7a77e374aded3d0

**Comment by akshaywali** [comment]
pushed in Update 1.5.7
