### ISSUE TITLE
Sanitization and output escaping missing in tab Upgrade to Pro

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/gn-publisher#49]
The GN Publisher plugin for WordPress is vulnerable to Reflected Cross-Site Scripting via the ‘tab’ parameter in versions up to, and including, 1.5.5 due to insufficient input sanitization and output escaping.

Ticket Ref: https://magazine3.in/conversation/105516?folder_id=25

**Comment by akshaywali** [comment]
pushed in update 1.5.6
