### ISSUE TITLE
Add compatibility with the plugin PublishPress Authors

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/gn-publisher#51]
Add compatibility with the plugin PublishPress Authors as the authors should appear in the different elements in the RSS feeds

Ref ticket: https://magazine3.in/conversation/122224?folder_id=27

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/gn-publisher-pro/commit/e47aac3b3e70b16f146ee4ff25b031e7fe333e9f

**Comment by akshaywali** [comment]
pushed in Update 1.5.7
