### ISSUE TITLE
no articles showing in our feed in Publisher Center.

### ISSUE THREAD

**Issue by mahendra2023** [ahmedkaludi/gn-publisher#66]
Since July 29, our articles are not getting indexed on the
Google News app. And there are no articles showing in our feed in Publisher
Center. While 6-7 articles are published everyday on our site.

publisher link:- https://news.google.com/publications/CAAqBwgKMPfswAswiYjYAw?ceid=IN:hi&oc=3

**Comment by Sanjeevsetu** [comment]
Hi @mahendra2023 

Sorry for delay in response. Are you still facing issue?? If Yes, Kindly reach out to us via https://gnpublisher.com/contact-us/.
