### ISSUE TITLE
Need to make a compatibility with the Molongui author profile plugin

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/gn-publisher#70]
Need to make a compatibility with the Molongui author profile plugin

Ref ticket:https://magazine3.in/conversation/185971?folder_id=29

**Comment by shridhamdeveloper** [comment]
Refer below commit for pro changes
https://github.com/ahmedkaludi/gn-publisher-pro/commit/cea9f545a12c105d90094b865d00066f990906fb
