### ISSUE TITLE
Need to add option to include pages in google news Feed

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/gn-publisher#76]
Need to add option to include pages in google news Feed 

Ref ticket: https://magazine3.in/conversation/213010?folder_id=29

**Comment by shridhamdeveloper** [comment]
Commit reference to pro
https://github.com/ahmedkaludi/gn-publisher-pro/commit/6a3ea29c4177b56ae7556e14a4401256f1d173c7
