### ISSUE TITLE
Warning after recent update Version 1.5.11

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/gn-publisher#79]
PHP Warning: Undefined array key "gnpub_google_rev_snippet" in /home/headfo/public_html/wp-content/plugins/gn-publisher/gn-publisher.php on line 312"

**Comment by MahmutHizal** [comment]
Confirmed.
```php
AH01071: Got error 'PHP message: PHP Warning: Undefined array key "gnpub_google_rev_snippet" in /var/www/vhosts/example.com/httpdocs/wp-content/plugins/gn-publisher/gn-publisher.php on line 312'
```

This error appears on every page of my website, and it affects the performance and loading time. I have tried to deactivate and reactivate the plugin, but the error persists. I have also checked the plugin settings, but I could not find any option related to the “gnpub_google_rev_snippet” array key. I am using the latest version of WordPress and the plugin.

**Comment by IvanZhuck** [comment]
As a temporary solution you can save plugin settings, it will create the option record in the DB.
![Screenshot from 2023-11-24 09-01-11](https://github.com/ahmedkaludi/gn-publisher/assets/9550657/18f92c11-b37f-4e46-afce-53950d471925)

**Comment by MohammedAkramU7** [comment]
Another users facing same issues
https://magazine3.in/conversation/216742?folder_id=21
https://magazine3.in/conversation/216845?folder_id=21
https://magazine3.in/conversation/216806?folder_id=21

**Comment by Sdaud1950** [comment]
same issue : 

https://magazine3.in/conversation/216811?folder_id=29

**Comment by Sanjeevsetu** [comment]
Pushed in 1.5.11.1
