### ISSUE TITLE
Issue with the sitemap date formatting.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/gn-publisher#82]
An invalid date was found. Please fix the date or formatting before resubmitting.

Ref ticket:https://magazine3.in/conversation/215574?folder_id=29

**Comment by Sanjeevsetu** [comment]
Ref: https://github.com/ahmedkaludi/gn-publisher-pro/commit/570724d256c396c4d04ebcc3b23c06c7680ed2ee
