### ISSUE TITLE
Guid is not being changed based on language feed in translatpress

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/gn-publisher#89]
https://magazine3.in/conversation/239166?folder_id=4

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/gn-publisher-pro/commit/d17852ebd6d3e144a9f7dede3c6f03c53c706bcd

**Comment by akshaywali** [comment]
pushed pro version 1.0.9
